### ISSUE TITLE
[guides] CURL Guide

### ISSUE THREAD

**Issue by joeyklee** [itp-dwd/2020-spring#10]
How to interface with a server / api / database

**Comment by catarak** [comment]
I added using Postman to the Week 3 curriculum in our [README](https://github.com/itp-dwd/2020-spring/blob/master/README.md). Maybe we can say what cURL is (since it's used in a lot of API documentation), but I honestly never use it because I can never remember the syntax without looking it up.

**Comment by joeyklee** [comment]
@catarak - you're totally right. CURL is great for quick tests, but I also struggle to remember all the right flags, etc. 

Maybe we can have a cURL cheatsheet in case peeps want to give it a try (and for our own sakes!) but focus on Postman usage for testing.

**Comment by joeyklee** [comment]
Hey @catarak - just fyi, I'm just jamming on the curl cheatsheet. Should be done shortly! :)

**Comment by joeyklee** [comment]
Done! 

See `guides/curl-cheatsheet.md`

p.s. Opening a separate guide for postman
