### ISSUE TITLE
[server side] How to install node

### ISSUE THREAD

**Issue by joeyklee** [itp-dwd/2020-spring#12]
How to install and use node:
https://www.taniarascia.com/how-to-install-and-use-node-js-and-npm-mac-and-windows/
* this might confuse more than it helps, but just a reference to get started

**Comment by catarak** [comment]
Do you think students should install Node using the Node installer, or use nvm (or [nvm-windows](https://github.com/coreybutler/nvm-windows))? The installer is obviously easier, but nvm isn't that much harder, and then you can easily change to any node version.

**Comment by joeyklee** [comment]
@catarak - Oh! The default node installer is the easiest BUT I do think it is v. important to know that installing different node versions is crucial. 

Let's go with installing via NVM and make a tutorial on this installation that includes why this is important, how to switch between node versions, etc.

**Comment by joeyklee** [comment]
Closing this since we have our guides/installing-nodejs.md
