### ISSUE TITLE
[meta] How to give feedback

### ISSUE THREAD

**Issue by joeyklee** [itp-dwd/2020-spring#19]
I love this piece about "How to talk to kids" as a way of deconstructing feedback, suggestions, advice, and critique. Regardless of whether we're talking to children or adults, this type of conscientiousness is amazing. 

https://www.theatlantic.com/family/archive/2018/06/mr-rogers-neighborhood-talking-to-kids/562352/

**Comment by catarak** [comment]
I love this! Here's some other stuff I've pulled together (in ICM, but wasn't quite sure how to use it):

## Giving Criticism

A short guide for offering constructive criticism, pulled from Golan Levin and Tega Brain's forthcoming book, _Code as Creative Medium: A Teacher's Manual_:

1. Description: What do you see?
2. Analysis: How is it made? What does it make you think about or feel?
3. Interpretation: What is it about? What is the main idea being explored?
4. Evaluation: Is it successful? Does it explore the prompt in a compelling, interesting or unique way?

## Receiving Criticism

Receiving criticism is a skill to develop alongside giving criticism. We are all giving time and energy to help each other with our work, so how can you receive critical feedback as generosity? How can you separate you, as an individual, and your identity from your work? 

It's also an important skill to be able to sort what is useful for you and what is not. It can sometimes be hard and triggering to receive criticism, and that's something to be mindful of as well. Here are some  "rules of the road" for receiving criticism, adapted from _The Artist's Way_ by Julia Cameron. 

1. Receive the criticism all the way through and get it over with.
2. Jot down notes to yourself on what concepts or phrases bother you.
3. Jot down notes on what concepts or phrases seem useful.
4. Do something very nuturing for yourself—read an old good review or recall a compliment.
5. Remember that even if you have made a truly rotten piece of art, it may be _necessary_ stepping-stone to your next work. Art matures spasmodically and _requires_ ugly-ducking growth stages.
6. Look at the criticism again. Does it remind of you any criticism from your past?
7. Write a letter to the critic—not to be mailed, most probably. Defend your work _and_ acknowledge what was helpful, if anything, in the criticism proffered.
8. Get back on the horse. Make an immediate commitment to do something creative.
9. Do it. Creativity is the only cure for criticism.

**Comment by joeyklee** [comment]
Added this also to the wiki: https://github.com/itp-dwd/2020-spring/wiki/How-to:-Feedback

Let's close this issue when ready! We can update/add refs to the wiki?

**Comment by joeyklee** [comment]
Closing this now!
