### ISSUE TITLE
Create form to submit homework

### ISSUE THREAD

**Issue by catarak** [itp-dwd/2020-spring#27]
Create a form for students to submit their homework that includes:
- Name
- Email
- Which assignment
- GitHub URL
- Deployment URL
- Questions

Open questions:
- Do we want the students to also do blog posts, or submit non-programming work?

**Comment by catarak** [comment]
Here's the form I've created so far: https://forms.gle/JV5RPkxvFuVBt2Gx6

**Comment by joeyklee** [comment]
Re form:
+ Brilliant! I will make a copy of this for my section

> Do we want the students to also do blog posts, or submit non-programming work?
+ I'd like to see students writing about their work and process and explain as much about what is going on as possible so in this way, yes, I'd say they should be submitting blog posts/write-ups. 
+ Maybe we can do it like, "every assignment/project must have a README.md file that explains, how to setup your project, and the steps you took to build the project...." That way students get into the modus of always making READMEs and documentation for their technical work. How do you feel about that?

**Comment by joeyklee** [comment]
Making a note that we should upate:

```
All assignments should be turned in BEFORE 2PM on Monday, the day of class.
```

We decided it would be 6PM on Sunday correct?

**Comment by catarak** [comment]
I think we decided midnight, since it still gives all day Monday for us to look over all of the assignments?

**Comment by joeyklee** [comment]
@catarak - Word. That sounds right. Ok. Let's change that on the submission forms :)

**Comment by catarak** [comment]
> @catarak - Word. That sounds right. Ok. Let's change that on the submission forms :)

just changed the hw form! 

> * Maybe we can do it like, "every assignment/project must have a README.md file that explains, how to setup your project, and the steps you took to build the project...." That way students get into the modus of always making READMEs and documentation for their technical work. How do you feel about that?

in your mind is this in addition to a blog post? or in lieu of one?

**Comment by joeyklee** [comment]
> just changed the hw form!
+ Awesome! Thank you!

> in your mind is this in addition to a blog post? or in lieu of one?
+ I would say that it is in lieu of one. Their READMEs should serve as their documentation with any additional notes and reflections included there. My hope is that it also gets the students into the practice of using git as much as possible.

**Comment by joeyklee** [comment]
Done! - closed
