### ISSUE TITLE
Create template for each week

### ISSUE THREAD

**Issue by catarak** [itp-dwd/2020-spring#28]
For reference:
- [ICM Weeks](https://github.com/ITPNYU/ICM-2019-Code/tree/master/weeks)
- [Eyebeam Workshop Template](https://github.com/eyebeam/curriculum/blob/master/TEMPLATE.md), probably overkill but I also like how explicit it is about a lot of things.

**Comment by catarak** [comment]
# Week Title

## Essential Questions
Questions that lead to meaningful exploration of CS concepts and practices. Examples:
- How can programming represent your ideas and beliefs?
- How might we use math to express ourselves creatively?
- How might we use computing to impact our community?
- What information is my computer sharing about me or my online activity?

## Introduction
Please provide a narrative of what the unit is about, and why we should learn it that is simple enough that a student could read and understand. Example: "In this workshop we will be using ... to explore ... so that you have a better understanding of how ...

### Outcomes & Goals
This can be easily answered by completing these example sentences:
* In this workshop we will be… (soldering, setting up a RPi home network, making a wearable that communicates with….)
* Students will walk away with a deeper understanding of…

## Topics
This section can have many subheaders (h3's). This should list all of the topic areas, (e.g. Git, Using the command line), with links to guides and references. 

## Pacing / Duration
Number of total hours the class session will take. Please try to take into account transition time between instruction and hands on exercises if any prep is necessary.

- Break down of the class schedule example: 
  - :15 Overview, context, examples and vocabulary 
  - :20 Instruction & hands on exercise 
  - :15 Wrap-up discussion & sharing, reflection or journal and next steps

## Materials Needed
What hardware, software, or other materials will students or teachers need for lessons.

### Exercises To Do Before Class
What materials (readings, tasks, exercises) should students complete before class to be prepared for the lesson.

### Vocabulary (example)
* Program: A procedure, or set of instructions, that performs a specific task when executed by a computer. 
* Programming Language: The human-readable commands and syntax (or grammar rules) used to write programs.

## Studio Exercise Descriptions
Descriptions of each exercise or phase of class. Similar to pacing but with more description of steps.

## References
Include any sources cited, but not directly linked in the unit.

**Comment by joeyklee** [comment]
oh! yes, I do love this template. I'm very in favor of using this to structure the weeklies.

**Comment by joeyklee** [comment]
@catarak - I added this template to the Wiki: https://github.com/itp-dwd/2020-spring/wiki/Curriculum-Template 

I'd say this is resolved/decided. Let's close this issue and work from the wiki template for updates? 

Thanks for this research + great ref!
