### ISSUE TITLE
[meta] Development on Windows

### ISSUE THREAD

**Issue by catarak** [itp-dwd/2020-spring#36]
As someone who has done software development exclusively on Mac and Linux, I have no idea how folks develop JS applications on Windows. Apparently they use a thing called "Windows Subsystem for Linux." I'm going to try installing it on my Windows machine and report back...

**Comment by joeyklee** [comment]
I've used Chocolatey https://chocolatey.org/ in the past... not sure what its status is though :/

**Comment by catarak** [comment]
So far I've been looking at https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/development_environment and https://docs.microsoft.com/en-us/windows/nodejs/setup-on-wsl2, looking good at the moment...

**Comment by catarak** [comment]
Issues I've run into so far:
- I enabled the Windows Insider Program, but then I manually had to check for Windows Updates in order to enable WSL 2 (which is apparently better than WSL 1)

**Comment by joeyklee** [comment]
Oh this reminds me - maybe we should ask what operating systems people are using in our Student Survey form to get a feeling for what might be in store?

**Comment by catarak** [comment]
definitely!

**Comment by catarak** [comment]
last snag in this installation process is when it says "Open your Ubuntu 18.04 command line," what that actually means is
1. open the windows command prompt
2. type `wsl` and hit enter
3. make sure it takes you to your home directory: `cd ~`

i'll quickly make a guide that has all of these things right now!

**Comment by joeyklee** [comment]
Closed with the guides/windows-setup.md
