### ISSUE TITLE
[content] SuperHi! Learn to Code Book

### ISSUE THREAD

**Issue by joeyklee** [itp-dwd/2020-spring#37]
Just got a copy of https://www.superhi.com/learn-to-code-now-book  for our reference, just fyi!

**Comment by catarak** [comment]
would love to look through it ✨

**Comment by joeyklee** [comment]
Just making a note: the book was just "ok.". Feels like it skims through some major details (e.g. Node.js is not mentioned as a server side language!!!!) and the tone didn't feel like my style (e.g. "coding will make you money").
