### ISSUE TITLE
.env ==> setting environment variables

### ISSUE THREAD

**Issue by joeyklee** [itp-dwd/2020-spring#79]
@catarak - we'll need to mention this for glitch, no?

**Comment by catarak** [comment]
Oh shoot, I meant to test server-side deployment to Glitch and didn't—in the workbook I was just using a `config.json` to not have to deal with explaining environment variables but it seems like we're gonna have to.

**Comment by catarak** [comment]
~I can add/update the examples in the workbook!~ Done ✨

**Comment by catarak** [comment]
I also updated A4—anything else you think we need to do?

**Comment by joeyklee** [comment]
This is also covered https://github.com/itp-dwd/2020-spring/blob/master/guides/mongodb-guide.md - closing now. Thanks! 🙏
